### ISSUE TITLE
/etc/resolv.conf not getting populated in ubuntu image

### ISSUE THREAD

**Issue by jstarks** [Microsoft/opengcs#78]
```docker run --rm ubuntu cat /etc/resolv.conf```

No output. This breaks DNS resolution inside containers.

**Comment by rn** [comment]
I made some changes to this a week or so ago via: https://github.com/Microsoft/opengcs/pull/63 I also left this rather length comment: https://github.com/Microsoft/opengcs/blob/master/service/gcs/core/gcs/gcs.go#L183

I did test DNS/`resolv.conf` at the the time and it worked with the changes in my PR (it didn't before for a variety of reasons, including that `/etc/resolv.conf` was written in an incorrect format). So maybe something else changed in the meantime...

**Comment by gupta-ak** [comment]
It shows up in both the `ubuntu` and `busybox` image. In the `busybox` image, it is actually populated, but in the `ubuntu` image it is not. @beweedon  any idea why?

**Comment by gupta-ak** [comment]
Ah, I read Rolf's comment and checked the `ubuntu` image. Turns out one of the `ubuntu` layers has an empty `resolv.conf` so `overlay` overrides it.

**Comment by rn** [comment]
yeah, I just noticed that as well.

If you look at the `json.conf` of a container on Linux you see (this is from a `docker run --rm -ti busybox /bin/sh` and then a `runc state <id>` which gives you directory of the bundle which contains the `config.json`):
```
[...]
{"destination":"/etc/resolv.conf","type":"bind","source":"/var/lib/docker/containers/
8a46042f5c5d7672895ad0c5357c9819bdfac3d939767c52010d301b2fc7c85b/resolv.conf","options":["rbind","rprivate"]},{"destination":"/etc/hostname","
type":"bind","source":"/var/lib/docker/containers/8a46042f5c5d7672895ad0c5357c9819bdfac3d939767c52010d301b2fc7c85b/hostname","options":["rbind
","rprivate"]},{"destination":"/etc/hosts","type":"bind","source":"/var/lib/docker/containers/8a46042f5c5d7672895ad0c5357c9819bdfac3d939767c52
010d301b2fc7c85b/hosts","options":["rbind","rprivate"]}
[...]
```
so this bind mounts a `resolv.conf`, `hostname`, and `hosts` into the container, effectively overwriting whatever is in the image. These bind mounts are not present in the `mounts` section of the `config.json` pass from the windows side to the utility VM. Hence my comment about bind mounts.

**Comment by beweedon** [comment]
If we want a temporary solution for this, we could have the GCS overlay the resolv.conf on top of the one in the container layers, rather than underneath it. If we want to mirror how it's done in Linux and have a resolv.conf mapped into the container in the OCI spec, though, we'd have to talk about how to support this in docker, in our GCS protocol, who should set the values in resolv.conf, etc. But yeah, as for now, those mounts aren't being passed to the GCS.

**Comment by gupta-ak** [comment]
It makes sense to me to have docker create the bind mount in the OCI spec. To determine the resolv.conf location, we already have each container isolated in `/tmp/gcs/<containerID>`, so we can add the `resolv.conf`, `hostname`, and `hosts` files there in the `CreateContainer` request by calling `generateResolvConfFile`.  After that, I think the rest will work the same.

**Comment by jstarks** [comment]
How will Docker know the source location for the bind mount?

**Comment by gupta-ak** [comment]
We can provide helper methods / constants in `Microsoft/opengcs/client` that tell docker where the paths should be located. We probably already need to do this anyway (upstream moby has harded paths inside the utility  VM). If we want to change the paths in the future, we can change it on our repo and then revendor in moby.

**Comment by gupta-ak** [comment]
The other option is to inject this information into the OCI spec in the GCS before passing to runC, but I'm not sure if we intend to modify the OCI spec from the docker

**Comment by rn** [comment]
FWIW I had contemplated adding `/etc/resolv.conf` to the top layer, however that wouldn't work for readonly containers, ie docker `run --read-only`. One option would be add a tempfs layer, which contains the files, and then mount it high up the overlay.

**Comment by benweedon** [comment]
I'm not sure if how high we stick the base layer in the overlay affects whether we have a problem with a readonly utility VM, but I might be missing something. I think the issue we'll run into on a readonly filesystem is that the DHCP configuration configures resolv.conf in /etc rather than in a tmpfs mount location. I like Akash's idea of storing files like resolv.conf and hosts on a per-container basis under `/tmp/gcs/<containerID>`, so I think the steps for solving this issue are as follows (let me know if you see anything wrong):

- Rather than using the constant `baseFilesPath` for the base files location, make it a per-container path
- Change the DHCP configuration script to write resolv.conf to the correct location under `/tmp/gcs/<containerID>/base` maybe. I don't even think the script we're using is source controlled, though. We may want to look into that, and look into how to pass the resolv.conf location into it, because it currently assumes resolv.conf is under /etc.
- Mount the base directory at the top of the overlay rather than the bottom

@jterry75 can look into making these changes if they seem good.

**Comment by beweedon** [comment]
I'm not sure if how high we stick the base layer in the overlay affects whether we have a problem with a readonly utility VM, but I might be missing something. I think the issue we'll run into on a readonly filesystem is that the DHCP configuration configures resolv.conf in /etc rather than in a tmpfs mount location. I like Akash's idea of storing files like resolv.conf and hosts on a per-container basis under `/tmp/gcs/<containerID>`, so I think the steps for solving this issue are as follows (let me know if you see anything wrong):

- Rather than using the constant `baseFilesPath` for the base files location, make it a per-container path
- Change the DHCP configuration script to write resolv.conf to the correct location under `/tmp/gcs/<containerID>/base` maybe. I don't even think the script we're using is source controlled, though. We may want to look into that, and look into how to pass the resolv.conf location into it, because it currently assumes resolv.conf is under /etc.
- Mount the base directory at the top of the overlay rather than the bottom

@jterry75 can look into making these changes if they seem good.

**Comment by jterry75** [comment]
Updates? If we are ok with this plan I will make the changes

**Comment by gupta-ak** [comment]
Ben's suggestion looks good to me. Go ahead

**Comment by jterry75** [comment]
In #95 I have fixed the root issue. However the other suggestions:
1. Don't use a constant `baseFilesPath` for the base files location.
2. Move to /tmp/gcs/<containerID>/base

Are going to cause problems because as far as I can tell the `/sbin/udhcpc_config.script` will have no way of knowing the `<containerID>` given that it is *before* a container is even created. I think it has to be at a constant location?

**Comment by gupta-ak** [comment]
The `/sbin/udhcpc_config.script` is called in `ExecProcess` so the container is created at that point. To support this, we would need to do a couple of things:

- In `CreateContainer`, instead of creating the etc folder in the `baseFilesPath`, we do something like `c.OS.MkdirAll(/tmp/gcs/<ID>/base/etc, 0700) `
- Pass the container id information to the network adaptor configuration in ExecProcess, so it knows which layer to set as base.
- Change the `/sbin/udhcpc_config.script` (prob bring into this repo) to take in a `resolv.conf` path instead of it being hardcoded.
